services:
  web:
    build: .
    container_name: sevgin-me-web
    restart: always
    env_file:
      - .env
    networks:
      - sevgin-net
      - proxy_default

networks:
  sevgin-net:
    external: true
  proxy_default:
    external: true
